### ISSUE TITLE
LESS &:extend(.clearfix) fails

### ISSUE THREAD

**Issue by alandraper** [madskristensen/WebCompiler#113]
The following does not compile, with an error of `(WebCompiler) extend ' .clearfix' has no matches`
Bootstrap uses this extensively. 

```LESS
.clearfix() {
  &:before,
  &:after {
    content: " "; // 1
    display: table; // 2
  }
  &:after {
    clear: both;
  }
}

p{
  &:extend(.clearfix all);
}
```
