### ISSUE TITLE
SASS minifier is bugged

### ISSUE THREAD

**Issue by midiway** [madskristensen/WebCompiler#138]
test.scss:
```SASS
.parent
{
	.child
	{
		width: 64px;
		height: 24px;
	}
}
```

tes.min.css output:

```CSS
.parent.child{width:64px;height:24px}
```
In the output CSS, there should be a space between .parent and .child
The bug started happening after I update the extension to v1.7.246
