### ISSUE TITLE
SASS compiler @at-root doesn't work well

### ISSUE THREAD

**Issue by kiyokura** [madskristensen/WebCompiler#217]
### Installed product versions
- Visual Studio: 2015 Professional Update 2
- This extension: 1.10.310

### Description
SASS compiler generates wrong css files about @at-root.
In version 1.10.306, It seems to be working well.

### Steps to recreate
1. Create a sass file using @at-root. For example:
```sass
.my-align {
  &__left {
    text-align: left;

    @at-root {
      span#{&} {
        display: block;
      }
    }
  }

  &__center {
    text-align: center;

    @at-root {
      span#{&} {
        display: block;
      }
    }
  }

  &__right {
    text-align: right;

    @at-root {
      span#{&} {
        display: block;
      }
    }
  }
}
```
2. Compile the sass file.

### Current behavior
A wrong css file is generated:
```css
.my-align__left {
  text-align: left; }
  .my-align__left span.my-align__left {
    display: block; }

.my-align__center {
  text-align: center; }
  .my-align__center span.my-align__center {
    display: block; }

.my-align__right {
  text-align: right; }
  .my-align__right span.my-align__right {
    display: block; }
```

### Expected behavior
I expect a css file under bellowing( generated by 1.10.306):
```css
/* generated by 1.10.306 */
.my-align__left {
  text-align: left; }
  span.my-align__left {
    display: block; }

.my-align__center {
  text-align: center; }
  span.my-align__center {
    display: block; }

.my-align__right {
  text-align: right; }
  span.my-align__right {
    display: block; }
```
