### ISSUE TITLE
SCSS compiler does not add new line characters after selectors

### ISSUE THREAD

**Issue by FameT** [madskristensen/WebCompiler#290]
### Installed product versions
- Visual Studio: Enterprise 2015 14.0.25431.01 Update 3
- This extension: 1.11.326

### Description
SCSS compiler does not add necessary new line characters after selectors even if they are placed on separate lines in source file.

### Steps to recreate
1. Create file "test.scss" in your project:
```css
.item-name {
	&:hover,
	&:active {
		color: #ff0000;
		}
	}
```
2. Compile it with Web Compiler
3. Check the resulting test.css file:
```css
.item-name:hover, .item-name:active {
  color: #ff0000;
}
```

### Current behavior
`.item-name:hover` and `.item-name:active` are placed on the same line.

### Expected behavior
`.item-name:hover` and `.item-name:active` are placed on a new line each, i.e:
```css
.item-name:hover,
.item-name:active {
  color: #ff0000;
}
```
