### ISSUE TITLE
Attempts and fails to convert CSS Variables in SASS file

### ISSUE THREAD

**Issue by rezalas** [madskristensen/WebCompiler#428]
### Installed product versions
- Visual Studio: 2019 Community
- This extension: 1.12.394 w/ Web Essentials 2019

### Description
I have a number of CSS variables I'd like to utilize in my SASS files to make theming more adaptable. However, when I place CSS variables into my SASS files Web Compiler attempts to change them into SASS variables and then shows invalid errors

### Steps to recreate
Create a test.scss file with the following contents.
```css
html {
    --hue: 210;
    --background: hsl(var(--hue), 20%, 12%);
}

.testClass {
    background: var(--background);
}
```

### Current behavior
When saved, this will throw an invalid number error: `argument $hue of hsl($hue, $saturation, $lightness) must be a number`.

### Expected behavior
CSS variables should be passed through cleanly to the output `.css` file without being converted to or processed as SASS. Alternatively, a compiler option to enable CSS variable pass-through for SASS would be sufficient.
