### ISSUE TITLE
New lines not being preserved when auto-format is invoked in Visual Studio

### ISSUE THREAD

**Issue by NoelAbrahams** [madskristensen/WebCompiler#432]
### Installed product versions
- Visual Studio: 2019 Community

### Steps to recreate
Add the following to a .scss file
```scss
.app__info {
    position: fixed;
    z-index: 5; // Sample comment

    &.modal > .app__info-modal {
        display: flex;
    }

    &.fade > .app__info-modal {
        opacity: 0;
    }
}
```

Hit Control+K, Control+D to format the document.

### Current behavior
The line starting `&.model >` moves up.

### Expected behavior
The new line should be preserved.

Note: Removing the comment fixes the issue.
