### ISSUE TITLE
Compiling mixins

### ISSUE THREAD

**Issue by t00ks** [madskristensen/WebCompiler#44]
Hi, I have come across a bug in the compilation of a mixin. I am using a loop like this:

```LESS
.height-loop(@height, @divider) when (@divider > 0) {
    &.h-@{divider} {
        height: @height * @divider;
    }
    .height-loop(@height, (@divider - 1));
}
```

and it seems to be ignoring the & on the second line so when it creates the css it produces code like 
```CSS
.class .h-1 { 
```
and not 
```CSS
.class.h-1 {
```
Note: This worked correctly in VS2013 and the old version of web essentials.

Thanks!
