### ISSUE TITLE
@use does not work

### ISSUE THREAD

**Issue by Bluejanis** [madskristensen/WebCompiler#441]
### Installed product versions
- Visual Studio: 2017 Professional
- This extension: 1.12.394

### Description
I am trying to get the @use syntax to work, but it is not recognized.
Visual Studio highlights the @use: Validation (CSS 4.0): "uses" is not a known '@' directive.
Also when using _variables.$test;_ Visual Studio throws compile error: 

>   Error 0: Invalid CSS after "...olor: variables": expected expression (e.g. 1px, bold), was ".$test;" (86, 32)

### Steps to recreate
1. Create partial module: _variables.scss and add a variable $test: #555;
2. Create regular module: site.scss
3. Add _'@use "variables";_ to the top of Site.scss
4. Add style to Site.scss
```
.test {
    background-color: variables.$test;
}
```

### Current behavior
Nothing and compile errors.

### Expected behavior
https://sass-lang.com/documentation/at-rules/use
@use can be used to import variables and other things from a partial module.

**Comment by ShawnDigital** [comment]
If I am correctly understanding this source its using **node-sass** which uses **libsass** and I found hidden on SASS' website (until you click a little arrow) a notice that @use its currently supported only by **dart-sass** and other platforms use @import for now so this is not a WebCompiler issue. 

~~Ran across this today. SASS warns to use this instead of @import but this apparently isn't handled by the Web Compiler out-of-the-box. I'm using 2019 v16.4 with 2019 Web Essentials extension.~~

~~This is top of scss file...~~

```SCSS
@use  ".\palette";

html, body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
```

~~This is compiled output which causes errors...~~

```SCSS
@use ".\palette";
html, body {
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; }
```
