### ISSUE TITLE
Hex code are replaced by color name

### ISSUE THREAD

**Issue by nimeshdhruve** [madskristensen/WebCompiler#53]
I am using Bootstrap 3 and I noticed that Hex Color code gets replaced by color name.
For example: normalize.less file has below class
```css
mark {
  background: #ff0;
  color: #000;
}
```
and in CSS it gets compiled to 

```css
mark {
  background: yellow;
  color: black;
}
```
I have gone thru existing issues but wasn't able to find any existing issue. Also this doesn't happen for all the cases for example:

```css
pre,
  blockquote {
	border: 1px solid #999;
	page-break-inside: avoid;
  } 
```
gets compiled to 
```css
pre,
 blockquote {
	border: 1px solid #999999;
	page-break-inside: avoid;
}
```
