### ISSUE TITLE
The /*comment*/ syntax causes all SCSS afterwards to not be included

### ISSUE THREAD

**Issue by chrismbarr** [madskristensen/WebCompiler#92]
With the most recent update (v 1.3.136) I've noticed that as soon as any SCSS with a multi-line comment is encountered, any following code does not seem to be included.

:computer: **compilerconfig.json** setup

```json
[
	{
		"inputFile": "sass/test.scss",
		"outputFile": "sass/test.css"
	}
]
```

:arrow_forward: **SCSS input:**
```SCSS
#test1{
	color: red;
}

/*#test2{
	color: blue;
}*/

#test3{
	color: green;
}
```

:x: **Incorrect CSS Output:** (missing the `#test3` selector that should appear after the comment)
```CSS
#test1 {
  color: red; }

/*#test2{
	color: blue;
}*/
```

However, switching to the single-line comments will fix this, so this is my temporary workaround
:arrow_forward: **SCSS input:**
```SCSS
#test1{
	color: red;
}

//#test2{
//	color: blue;
//}

#test3{
	color: green;
}
```
:white_check_mark: **Correct CSS Output:** (Comments not included, and only uncommented code is output)
```CSS
#test1{
	color: red; }

#test3{
	color: green; }
```
